-- ----------------------------
-- Table structure for "C##FHBOOT"."TB_STOREBOOKSTORE"
-- ----------------------------
-- DROP TABLE "C##FHBOOT"."TB_STOREBOOKSTORE";
CREATE TABLE "C##FHBOOT"."TB_STOREBOOKSTORE" (
	"STORE_MANAGER_ID" NUMBER(0) NULL ,
	"STORE_PHONE_NUM" VARCHAR2(16 BYTE) NULL ,
	"STORE_TELEPHONE" VARCHAR2(16 BYTE) NULL ,
	"STORE_NAME" VARCHAR2(64 BYTE) NULL ,
	"STORE_POSITION" VARCHAR2(128 BYTE) NULL ,
	"BOOKSTORE_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "C##FHBOOT"."TB_STOREBOOKSTORE"."STORE_MANAGER_ID" IS '备注2';
COMMENT ON COLUMN "C##FHBOOT"."TB_STOREBOOKSTORE"."STORE_PHONE_NUM" IS '备注3';
COMMENT ON COLUMN "C##FHBOOT"."TB_STOREBOOKSTORE"."STORE_TELEPHONE" IS '备注4';
COMMENT ON COLUMN "C##FHBOOT"."TB_STOREBOOKSTORE"."STORE_NAME" IS '备注5';
COMMENT ON COLUMN "C##FHBOOT"."TB_STOREBOOKSTORE"."STORE_POSITION" IS '备注6';
COMMENT ON COLUMN "C##FHBOOT"."TB_STOREBOOKSTORE"."BOOKSTORE_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table TB_STOREBOOKSTORE
-- ----------------------------

-- ----------------------------
-- Checks structure for table "C##FHBOOT"."TB_STOREBOOKSTORE"

-- ----------------------------

ALTER TABLE "C##FHBOOT"."TB_STOREBOOKSTORE" ADD CHECK ("BOOKSTORE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "C##FHBOOT"."TB_STOREBOOKSTORE"
-- ----------------------------
ALTER TABLE "C##FHBOOT"."TB_STOREBOOKSTORE" ADD PRIMARY KEY ("BOOKSTORE_ID");
