
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `TB_STOREBOOKSTORE`
-- ----------------------------
DROP TABLE IF EXISTS `TB_STOREBOOKSTORE`;
CREATE TABLE `TB_STOREBOOKSTORE` (
 		`BOOKSTORE_ID` varchar(100) NOT NULL,
		`STORE_MANAGER_ID` int(0) NOT NULL COMMENT '备注2',
		`STORE_PHONE_NUM` varchar(16) DEFAULT NULL COMMENT '备注3',
		`STORE_TELEPHONE` varchar(16) DEFAULT NULL COMMENT '备注4',
		`STORE_NAME` varchar(64) DEFAULT NULL COMMENT '备注5',
		`STORE_POSITION` varchar(128) DEFAULT NULL COMMENT '备注6',
  		PRIMARY KEY (`BOOKSTORE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
