GO
/****** FHQQ313596790 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TB_STOREBOOKSTORE (
 		BOOKSTORE_ID  nvarchar(100) NOT NULL,
		STORE_MANAGER_ID int NOT NULL,
		STORE_PHONE_NUM nvarchar(16) DEFAULT NULL,
		STORE_TELEPHONE nvarchar(16) DEFAULT NULL,
		STORE_NAME nvarchar(64) DEFAULT NULL,
		STORE_POSITION nvarchar(128) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[BOOKSTORE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
